udpated deployment to render html for prod

diff --git a/deploy-public b/deploy-public
--- a/deploy-public
+++ b/deploy-public
@@ -93,13 +93,23 @@ read -d '' INDEX_HTML_TEMPLATE << EOF
     <redoc spec-url='https://raw.githubusercontent.com/Rhumbix/docs.rhumbix.com/master/$THIS_ENV/swagger-public-api-docs.json'></redoc>
     <script src="https://rebilly.github.io/ReDoc/releases/v1.18.1/redoc.min.js"> </script>
   </body>
+</html>
 EOF
 
-if echo $INDEX_HTML_TEMPLATE >> "$OUTDIR/index.html"; then
+if echo $INDEX_HTML_TEMPLATE > "$OUTDIR/index.html"; then
     echo -e "${GREEN}* New index rendered for $THIS_ENV: $OUTDIR/index.html${NC}"
 else
     echo -e "Could not print index html template to $OUTDIR/index.html"
     exit 1
+fi
+
+if [ $IS_PROD == true ]; then
+    if echo $INDEX_HTML_TEMPLATE > "$THISDIR/index.html"; then
+        echo -e "${BLUE}*! Bonus index rendered for prod: $THISDIR/index.html${NC}"
+    else
+        echo -e "Could not print index html template to $THISDIR/index.html"
+        exit 1
+    fi
 fi
 
 git status
